spring:
  application:
    name: "coinbreak-backend"
  datasource:
    url: jdbc:postgresql://localhost:5432/coinbreak
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  shutdown: GRACEFUL
  port: 8080

eth:
  chain_id: 1
  endpoint:
    url: https://ethereum-rpc.publicnode.com
  gas:
    limit: 9000000
    price: 4100000000

contract:
  erc20:
    usdt: 0xdAC17F958D2ee523a2206206994597C13D831ec7
    usdc: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
    bnb: 0xB8c77482e45F1F44dE1745F52C74426C631bDD52

